// Imports
import ___CSS_LOADER_API_SOURCEMAP_IMPORT___ from "../../../../node_modules/css-loader/dist/runtime/cssWithMappingToString.js";
import ___CSS_LOADER_API_IMPORT___ from "../../../../node_modules/css-loader/dist/runtime/api.js";
var ___CSS_LOADER_EXPORT___ = ___CSS_LOADER_API_IMPORT___(___CSS_LOADER_API_SOURCEMAP_IMPORT___);
// Module
___CSS_LOADER_EXPORT___.push([module.id, ".fwM0jNteIF0XH2dKuGs00g\\=\\={box-sizing:border-box !important}", "",{"version":3,"sources":["webpack://./src/components/Canvas/MaterialComponents/MaterialSwitch.module.scss"],"names":[],"mappings":"AAAA,4BACI,gCAAA","sourcesContent":[".boxSizing{\n    box-sizing: border-box !important;\n}"],"sourceRoot":""}]);
// Exports
___CSS_LOADER_EXPORT___.locals = {
	"boxSizing": "fwM0jNteIF0XH2dKuGs00g=="
};
export default ___CSS_LOADER_EXPORT___;
